version: '3'
services:
  db:
    image: alpine/sqlite
    volumes:
      - ./olx.db:/olx.db
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PATH=/olx.db