// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Usuario struct {
	ID       int64
	Nome     string
	Cpf      string
	Telefone string
	Dia      string
	Mes      string
	Ano      string
	ChavePix string
}
