// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: usuarios.sql

package db

import (
	"database/sql"

	_ "github.com/lib/pq"
)

type Queries struct {
	db *sql.DB
}

func NewQueries(db *sql.DB) *Queries {
	return &Queries{db: db}
}

const criarUsuario = `-- name: CriarUsuario :exec
INSERT INTO usuarios (nome, cpf, telefone, dia, mes, ano, chave_pix, email, senha)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CriarUsuarioParams struct {
	Nome     string
	Cpf      string
	Telefone string
	Dia      string
	Mes      string
	Ano      string
	ChavePix string
	Email 	 string
	Senha    string
}

func (q *Queries) CriarUsuario(arg CriarUsuarioParams) error {
	_, err := q.db.Exec(criarUsuario,
		arg.Nome,
		arg.Cpf,
		arg.Telefone,
		arg.Dia,
		arg.Mes,
		arg.Ano,
		arg.ChavePix,
		arg.Email,
		arg.Senha,
	)
	return err
}