// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: usuarios.sql

package db

import (
	"context"
)

const criarUsuario = `-- name: CriarUsuario :exec
INSERT INTO usuarios (nome, cpf, telefone, dia, mes, ano, chave_pix)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

const ListarUsuarios = `-- name: ListarUsuarios :many
SELECT * FROM usuarios;`

type CriarUsuarioParams struct {
	Nome     string
	Cpf      string
	Telefone string
	Dia      string
	Mes      string
	Ano      string
	ChavePix string
}

// sql/queries/usuarios.sql
func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, criarUsuario,
		arg.Nome,
		arg.Cpf,
		arg.Telefone,
		arg.Dia,
		arg.Mes,
		arg.Ano,
		arg.ChavePix,
	)
	return err
}
